### ISSUE TITLE
建议增加弹窗提示

### ISSUE THREAD

**Issue by ShukriChiu** [JavisPeng/taojinbi#1]
目前脚本运行的时候无任何弹窗提示，体验不佳，在执行任务的时候可以提供一个弹窗显示任务执行进度。

**Comment by JavisPeng** [comment]
新版本v1.0.3已经有消息提示，若需要console打印消息，可以取消注释第一行。  没有默认开启console提示，是因为有些任务需要按坐标点击，console可能会遮挡坐标位置

**Comment by JavisPeng** [comment]
@ShukriChiu   版本1.1.0已经添加了选择显示功能
