### ISSUE TITLE
账号黑了，任务百分比实际给的比做的低很多……

### ISSUE THREAD

**Issue by ctt0124** [JavisPeng/taojinbi#10]

**Comment by JavisPeng** [comment]
我的好像是正常的，金币每天奖励400-500不等， 昨天收益为517金币。你之前是不是还运行过啥程序？

**Comment by ctt0124** [comment]
试下来先不点上活力中心就没事。难道是淘宝的bug？。。
anyway谢谢老铁了！

**Comment by dotama** [comment]
同样的被系统制裁了,明日金币收益百分比和做任务赚金币里面显示的百分比不一致

**Comment by JavisPeng** [comment]
@dotama  可以尝试清理下淘宝本地数据试试，另外我查看最近今天的收益每天都是400金币左右

**Comment by dotama** [comment]
> @dotama 可以尝试清理下淘宝本地数据试试，另外我查看最近今天的收益每天都是400金币左右

恩，清理过了，但是已经制裁了的部分还是不会变。清理数据之后我测试了小号没有这个问题，也可能是由于我这的大号在ios登录过所导致。明天试试完全不登录ios, 看看大号收益和任务百分比是否一致。
