### ISSUE TITLE
目前已知的一些问题

### ISSUE THREAD

**Issue by kinver** [JavisPeng/taojinbi#105]
1.现在更新了很多任务需要下滑才能计时，其他issues已经提及了，我总结一下。目前只有“为你精选”会下滑，其它需要下滑但不会下滑的有：
~~精选(和为你精选不同)~~ 今天可以滑动了
高比例折扣
猜你喜欢
聚划算超级抵钱
淘金币专属爆款
我不记得还有没有了，到时想起来再编辑吧。
2.小说现在变成点进去一本书阅读10s了。
3.消消乐关卡变了。
4.小鸡那个只需要点一下就行了，以前的js都是点一下直接返回就行了，现在的js变成等15s再返回了，可以改回去。
~~5.天猫那个任务不用下app也行，直接在第一个页面就能计时。~~ ~~已失效，还是要天猫app了~~ 有时可以有时不可以神神经经的

**Comment by X156** [comment]
猜你喜欢那个任务不能下滑，只要运行就无限重复卡在那里

**Comment by cocomine** [comment]
[https://github.com/JavisPeng/taojinbi/pull/103](https://github.com/JavisPeng/taojinbi/pull/103)
上面的拉請求已經解決了所有需要下滑的任務, 等待作者確認
可以自行先更改代碼

**Comment by cocomine** [comment]
剩下第二和第三&4需要解決
