### ISSUE TITLE
867行报错解决

### ISSUE THREAD

**Issue by 67here** [JavisPeng/taojinbi#106]
找到解决方案了
方案1是 791行
把这行的花括号和两边的注释符删掉，保持和上下一样的格式就可以了(我发代码 直接就被屏蔽了，只能口述)
就可以正常运行了
不行的话，方案2
直接把报错的867行那里直接注释掉，或者删掉，只不过代价就是没有星秀猫任务，不过本来淘宝就会检测，无所谓

另外，谢谢巨佬的更新

**Comment by gui8912** [comment]
<button id="btn_miaomiao" text="单独执行618喵喵任务" />，还是无法运行啊

**Comment by gui8912** [comment]
《button id="btn_miaomiao" text="单独执行618喵喵任务" /》

**Comment by gui8912** [comment]
为了发出，特意改为中文的书名号

**Comment by 67here** [comment]
> 为了发出，特意改为中文的书名号

不行的话，你直接注释掉867行，就行了，不过这样星秀猫任务就没有了，不过本来有没有都差不多

**Comment by Wolverinetracy** [comment]
第791行的注释问题 改了确实不行

**Comment by JavisPeng** [comment]
不好意思，昨天晚上突然有事，忘记修改了，把注释去掉正常运行，但是喵币任务只+200
