### ISSUE TITLE
建议“浏览好店领金币”增加“领取5淘金币”功能

### ISSUE THREAD

**Issue by flyklts** [JavisPeng/taojinbi#107]
“浏览好店领金币”中部分店铺会有0-2个商品带“领取5淘金币”按钮，在浏览10秒的同时，可以同时在5秒内完成2次 “点击商品”、“立刻返回”动作，可多领取最多2*5=10个淘金币

**Comment by JavisPeng** [comment]
好的，最近有点忙，有时间可以看下
