### ISSUE TITLE
经过反复测试验证发现的一些问题

### ISSUE THREAD

**Issue by MarsTLBAD** [JavisPeng/taojinbi#108]
希望作者能看到！！！
希望作者能看到！！！
希望作者能看到！！！
1.滑动——老问题了！！！
①精选
②高比例折扣
③猜你喜欢
④聚划算超级抵钱
⑤淘金币专属爆款
注意！！！这些任务仅滑动一次不够，经过反复测试发现，需要至少连续地上下滑动十秒以上才能完成任务，而且只有上划或者只有下滑的操作也是不行的，下滑是浏览，上划的时候上方会提示“已浏览X秒，继续滑动得能量”，在我不停地上下连续滑动十秒后才能完成任务！记住是连续！既要上划！也要下滑！
2.看小说要随便点一本书看10秒
3.消消乐要随便执行三次消除

**Comment by JavisPeng** [comment]
这个问题有点多：
1.  关于下滑任务，可以在配置页面自定义关键字，之前测试一直下滑是没有问题的
2. 看小说问题，有时间在看看

**Comment by cjy2021** [comment]
> 这个问题有点多：
> 
> 1. 关于下滑任务，可以在配置页面自定义关键字，之前测试一直下滑是没有问题的
> 2. 看小说问题，有时间在看看

淘金币成就一直没法做，很多金币呢
