### ISSUE TITLE
又给大佬提建议：纠错问题

### ISSUE THREAD

**Issue by jw10126121** [JavisPeng/taojinbi#11]
1、自动纠错问题：
发现我的小米8SE常常会出现页面乱跳的情况，希望能加个判断当前任务页面判断，如果没在当前任务页面，自动跳回的功能。
可以判断当前activity与任务activity是否一致，但是业务逻辑可能相对麻烦一点。
2、大佬有交流群吗？希望关于autojs有更方便的交流，多学点大佬的知识。

**Comment by JavisPeng** [comment]
@jw10126121 
1. 下个版本在循环执行任务结束的时候，会对当前界面是否为任务列表的检测
2. 目前没有交流群，你可以直接加autojs的官方群
