### ISSUE TITLE
一个跳转的捷径

### ISSUE THREAD

**Issue by 67here** [JavisPeng/taojinbi#110]
我就不发pull request了

我花了点时间，用浏览器 扒到了淘宝的淘金币页面的url scheme，缩减了下链接长度，
可以直接跳转过去

app.startActivity({
    packageName: "com.taobao.taobao",
    data: 'taobao://market.m.taobao.com/app/tmall-wireless/tjb-2018/index/index.html'
    });

如果想直接跳转到淘金币的任务界面

app.startActivity({
    packageName: "com.taobao.taobao",
    data: 'taobao://pages.tmall.com/wow/z/tmtjb/town/task'
});

**Comment by MarsTLBAD** [comment]
这个可以有，但不知道可能存在的开屏广告以及弹出广告会不会对跳转界面造成影响、、、其实这个taojinbi脚本目前存在最大的问题是要实现连续的、不间断的上下滑动某些任务页面，但我不知道swipe该怎么修改、、、

**Comment by 67here** [comment]
> 这个可以有，但不知道可能存在的开屏广告以及弹出广告会不会对跳转界面造成影响、、、其实这个taojinbi脚本目前存在最大的问题是要实现连续的、不间断的上下滑动某些任务页面，但我不知道swipe该怎么修改、、、

这个东西可以无视广告的，直接跳，；不间断的话，加个while不断执行吧，滑动的那块我没看，我的手机运行滑动任务是没问题的

**Comment by JavisPeng** [comment]
好的，明天试试看看

**Comment by JavisPeng** [comment]
@67here 这种跳转方式比较方便，有时间可否指教下

**Comment by 67here** [comment]
> @67here 这种跳转方式比较方便，有时间可否指教下

我出了个视频 今天才更新完
https://www.bilibili.com/video/BV1dg41137rx?p=1

**Comment by dadaoerv** [comment]
使用反馈，感谢大佬的辛苦工作。一加8手机Android11系统，淘宝10.1.0，一次运行除了消消乐都完成（我的消消乐1080关）能量值3100完成，realme Q2手机，Android11系统，淘宝10.1.0，排列与一加手机不一样，2次运行，完成能量值2900.
