### ISSUE TITLE
芭芭农场 大部分时候提示无法执行

### ISSUE THREAD

**Issue by LvDeShei** [JavisPeng/taojinbi#111]
小米5X，MIUI11，安卓8.1，手机淘宝10.0.0
执行的时候进入淘宝首页后，不动了！
然后返回退出，到本工具界面运行提示那里看到“...请重新运行...”
有时候就行，10回有9回不行！
可能是我手机淘宝10.0.0这个版本的问题，因为大神在MD中提示用的是9.0***的版本，祈盼大神关注下，辛苦了！

**Comment by JavisPeng** [comment]
好的，明天有时间回去调试
