### ISSUE TITLE
请问，有没有针对京东618活动的app

### ISSUE THREAD

**Issue by LvDeShei** [JavisPeng/taojinbi#112]
鉴于在GitHub上的所有京东签到都被封停了，所以想问一下作者有没有计划开发类似于猫币的安卓app，付费也可以的！谢谢

**Comment by 67here** [comment]
没有的，不可能的，控件全被隐藏了，
除非图色+坐标点击，但是那个工作量会大很多，频繁的截图对手机要求也不低

**Comment by JavisPeng** [comment]
2楼说得对，维护不过来
