### ISSUE TITLE
从1.7.1升级到最新1.7.2后的问题

### ISSUE THREAD

**Issue by LvDeShei** [JavisPeng/taojinbi#114]
手机：小米5X
MIUI：11
安卓：8.1
淘宝10.1.0双开，今早从1.7.1更新至最新版1.7.2，在启用工具选择芭芭农场进入淘宝页面后接着再次调用双开选择让再次选择。

请关注！

**Comment by JavisPeng** [comment]
双开是啥，我这边没有？
