### ISSUE TITLE
华为P30pro以及三星S6报错

### ISSUE THREAD

**Issue by tygwd1** [JavisPeng/taojinbi#118]
貌似昨天还正常使用，今天就全线报错

**Comment by tygwd1** [comment]
08:46:15.009/E: Thread[main (Spawn-1),5]: TypeError: Cannot call method "child" of null (/data/user/0/com.taojinbi486/files/project/taojinbi.js#107)
TypeError: Cannot call method "child" of null
    at get_task (/data/user/0/com.taojinbi486/files/project/taojinbi.js:107:0)
    at do_simple_task (/data/user/0/com.taojinbi486/files/project/taojinbi.js:449:0)
    at taojinbi_task (/data/user/0/com.taojinbi486/files/project/taojinbi.js:527:0)
    at main (/data/user/0/com.taojinbi486/files/project/taojinbi.js:571:0)
    at /data/user/0/com.taojinbi486/files/project/taojinbi.js:874:0

**Comment by joke2003** [comment]
华为P40 Pro也报上面这个错误，不管是1.7.1，还是1.7.2

**Comment by branchGit** [comment]
一样报错，估计是某宝更新了。。。。

**Comment by ctt0124** [comment]
line107，去掉最后的 .child(0) 就可以了

**Comment by dadaoerv** [comment]
楼上的方法不行，删掉107行，直接无法运行了。
可用方法：1. 手动签到领昨天的币，2. 淘宝养猫自己完成。3，开始后的第一个签到任务自己点一下。后面就下去了。

**Comment by Arrebo** [comment]
华为p30也是这个错误

**Comment by flyklts** [comment]
老版本也是这个问题

**Comment by tygwd1** [comment]
经过网友dadaoerv的反馈，他的办法可以通过大部分项目，但后期会在芭芭农场报错，但索性剩余项目不多了，手动完成。但仍希望作者尽快更新！感谢dadaoerv，感谢作者的无私奉献！

**Comment by fanjohn163** [comment]
在“任务执行按钮关键字”中删除“去看看”就可以

**Comment by JavisPeng** [comment]
最近加班，周末有时间我再测试下
