### ISSUE TITLE
关于最新版淘金币运行失败报错的解决办法

### ISSUE THREAD

**Issue by MarsTLBAD** [JavisPeng/taojinbi#122]
解决办法：参数配置，任务执行按钮关键字，删掉最后面的“去看看”，然后运行就没问题了
——————————————————————————————————————————————————————
吐槽：另外，作者写完脚本自己都不测试一下的么？保存当前配置之后下次打开根本不变还是原样
手机型号是K30Pro，屏幕分辨率是2400*1800
最核心的某些页面浏览滑动Bug，在参数配置中添加了“任务浏览下滑关键字”根本不起作用，看源码用swipe直接取device的height和width，但是实际测试并没有滑动

**Comment by 67here** [comment]
那个"去看看"是或的关系，不会影响的，报错是因为时间太短 ，来不及找控件，加一句话就行了，上传pull reque里了

**Comment by kinghunki** [comment]
> 那个"去看看"是或的关系，不会影响的，报错是因为时间太短 ，来不及找控件，加一句话就行了，上传pull reque里了

这个方法测试不行!删除去看看才可以！

**Comment by edison0354** [comment]
你需要点击“加载配置”

**Comment by JavisPeng** [comment]
每次都是测试完，在提交代码，具体问题 我再看看

**Comment by STC214** [comment]
奈斯 
楼主方法切实有效

**Comment by JavisPeng** [comment]
@MarsTLBAD 保存当前配置之后下次打开根本不变还是原样
保存后，需要加载一次，因为程序比较依赖该配置，若用户修改错了，可能会导致无法运行
