### ISSUE TITLE
1.7.2一直无法自动更新到1.7.3

### ISSUE THREAD

**Issue by moneyyes** [JavisPeng/taojinbi#124]
感谢作者一直的更新~

三星note9，8.1系统
以前的自动更新都是一启动就提示的
现在一直还停留在1.7.2没有提示有更新

不过618过了以后1.7.2也回到不用任何修改也能正常运行就是了……

**Comment by MarsTLBAD** [comment]
我一直都是手动下载taojinbi.js覆盖原文件的

**Comment by schalkiii** [comment]
+1，也是三星ROM 。不知道其他ROM是否也存一样的问题

**Comment by 3828669** [comment]
怎么我从来没见提示更新！！都是自己来看看

**Comment by branchGit** [comment]
从来没自动更新过啊

**Comment by JavisPeng** [comment]
@MarsTLBAD 要下周release页面的apk才行

**Comment by JavisPeng** [comment]
@moneyyes  我晚上回去看下，可能代码没有上传

**Comment by moneyyes** [comment]
> @moneyyes 我晚上回去看下，可能代码没有上传

新版已解决，感谢~
