### ISSUE TITLE
逛好店领淘金币被风控了

### ISSUE THREAD

**Issue by ghost** [JavisPeng/taojinbi#13]
![微信图片_20201225085805](https://user-images.githubusercontent.com/47102413/103112289-5aa59200-468f-11eb-9ad6-0e44857677f1.jpg)

**Comment by JavisPeng** [comment]
@ABBCzar   奇怪，我今天在P30Pro测试了2个账号，这个活动都是正常的啊

**Comment by sea1636** [comment]
前天风控，今天就没问题了！
