### ISSUE TITLE
每次都卡在这个界面

### ISSUE THREAD

**Issue by Zayia** [JavisPeng/taojinbi#15]
![photo_2020-12-28_09-27-02](https://user-images.githubusercontent.com/35530837/103183687-ea278c80-48ab-11eb-86fd-55c2be1f0b0a.jpg)

**Comment by JavisPeng** [comment]
这个弹窗是淘宝前几天加的，你使用的文件版本是v1.3.6 ？
```
v1.3.6 2020年12月24日19:22:57
解决消消乐完成消除回到主界面，出现[再玩一次]弹窗问题
```

**Comment by Zayia** [comment]
> 这个弹窗是淘宝前几天加的，你使用的文件版本是v1.3.6 ？
> 
> ```
> v1.3.6 2020年12月24日19:22:57
> 解决消消乐完成消除回到主界面，出现[再玩一次]弹窗问题
> ```

我记得我更新了啊，昨天又更新了一下，好像是没问题了

**Comment by Zayia** [comment]
还是有这个问题
最新版本还是会卡在这个界面，之前的版本也是会卡在这个界面
![Screenshot_20210112-111249](https://user-images.githubusercontent.com/35530837/104300924-fa9c5180-54be-11eb-99d0-c80767344a48.jpg)

**Comment by Sirius2s** [comment]
还是手动做消消乐任务吧

@JavisPeng 1.4.1版 店铺关注+10金币还是不行（关注成功、但不给金币）；我自己换press方法操作也是这样。别人运行的不知道有没有收到+10的

**Comment by JavisPeng** [comment]
Sirius2s 我昨天关注店铺是给了10金币金币奖励的
[10金币金币奖励](https://img-blog.csdnimg.cn/20210113103939677.jpg)

**Comment by JavisPeng** [comment]
@Zayia 我刚刚测试了下，在我手机上没有问题，可能和网络卡顿有关，下个版本我把等待时间设置长一点

**Comment by Sirius2s** [comment]
那可能是我tb版本v9.4的原因

**Comment by JavisPeng** [comment]
```
    //再挑战?
    cs_click(5, '#ffffff', 0.6, 0.15, 0.35, 0.5); sleep(800)
```
可能是网络问题，新版把等待再挑战弹窗时间设置为了5秒
