### ISSUE TITLE
可否 支持 iphone

### ISSUE THREAD

**Issue by moruoxian** [JavisPeng/taojinbi#17]

**Comment by JavisPeng** [comment]
@moruoxian 抱歉，目前只支持安卓机

**Comment by Sirius2s** [comment]
@moruoxian iphone 可以看这个项目[leecobaby/shortcuts](https://github.com/leecobaby/shortcuts)

**Comment by moruoxian** [comment]
> @moruoxian iphone 可以看这个项目[leecobaby/shortcuts](https://github.com/leecobaby/shortcuts)

好的 试过了 是放到捷径中打开的是吧 这个捷径功能点还是比较少 而且 关不掉不知道为什么
