### ISSUE TITLE
[消消乐任务]不稳

### ISSUE THREAD

**Issue by Sirius2s** [JavisPeng/taojinbi#22]
[消消乐任务]模块：建议根据游戏自动提示的操作步骤[活动块高亮边缘]来操作；根据右上方“任务完成”文字或打勾图标变化来结束任务，做返回操作。
有空再弄吧

预祝顺利入职，薪水多多！

**Comment by JavisPeng** [comment]
@Sirius2s 这个涉及到截图分析，操作步骤有点繁琐

**Comment by jw10126121** [comment]
提个问题，有些taobao是有多开分身的，能否添加tb分身运行功能

**Comment by JavisPeng** [comment]
@jw10126121  autojs好像无法实现分身功能
