### ISSUE TITLE
天天红包赛搬家

### ISSUE THREAD

**Issue by Aaronoooooo** [JavisPeng/taojinbi#23]
1.需关注运动银行
2.进入我的淘宝,我的运动
3.进入天天红包赛

**Comment by JavisPeng** [comment]
@supremesup  我的淘金币怎么没有这个活动

**Comment by Aaronoooooo** [comment]
> @supremesup 我的淘金币怎么没有这个活动

我是9.17.0的

**Comment by JavisPeng** [comment]
v1.3.11已修复该问题

**Comment by Aaronoooooo** [comment]
> v1.3.11已修复该问题

老板威武
