### ISSUE TITLE
Autojs 4.1.1执行新的JS脚本貌似报错？

### ISSUE THREAD

**Issue by jackdiy** [JavisPeng/taojinbi#24]
Autojs 4.1.1执行新的JS脚本貌似报错？

**Comment by JavisPeng** [comment]
@jackdiy  具体啥错误，可以截个图？

**Comment by jackdiy** [comment]
Auto.js：错误：SyntaxError：invalid object initializer (/storage/emulated/0/脚本/taojinbi_v1.3.10.js#522)

**Comment by JavisPeng** [comment]
我刚测试了最新代码没有问题，另外很奇怪，v1.3.10.js只有449行，你那边脚本提示522行报错了，你是否还复制了其他内容

**Comment by jackdiy** [comment]
Sorry，我发现问题所在了，不能直接用GitHub上的下载Js会出来个300多KB的，本质上复制内容下来只有449行，18kb，是我的问题。但不知何故之前我同样的操作方式旧版本没问题。但这应该是个新手的脑残问题了
