### ISSUE TITLE
悬浮窗权限

### ISSUE THREAD

**Issue by Aaronoooooo** [JavisPeng/taojinbi#25]
点赞蚂蚁森林收能量🌹🌹🌹
1.蚂蚁庄园喂小鸡任务(提示无悬浮窗权限)
支付宝和淘宝悬浮窗权限均以打开
2.淘金币抢金条x120能量任务(默认抢第一个任务,不一定抢到金条任务,我的抢金条排在了第三)
嘻嘻嘻,以上是试用反馈,谢谢大佬的贡献

**Comment by JavisPeng** [comment]
1.这个可能是autojs的历史问题，和部分机型有关
2.每天抢商品都在更新，而且不一定每天都有金条可抢，默认下注第一个可抢的商品

**Comment by Aaronoooooo** [comment]
> 1.这个可能是autojs的历史问题，和部分机型有关
> 2.每天抢商品都在更新，而且不一定每天都有金条可抢，默认下注第一个可抢的商品

好嘞,感谢感谢

**Comment by Aaronoooooo** [comment]
> > 1.这个可能是autojs的历史问题，和部分机型有关
> > 2.每天抢商品都在更新，而且不一定每天都有金条可抢，默认下注第一个可抢的商品
> 
> 好嘞,感谢感谢

是不是理论是,所有操作都可以通过auto.js来实现呀,想要学习玩一玩,嘿嘿嘿

**Comment by JavisPeng** [comment]
不是，比如消消乐和掷色子就获取不到对应的控件，需要截图分析

**Comment by Aaronoooooo** [comment]
> 不是，比如消消乐和掷色子就获取不到对应的控件，需要截图分析

了解了
