### ISSUE TITLE
小白求解刷tjb有什么用

### ISSUE THREAD

**Issue by chimpan** [JavisPeng/taojinbi#26]
小白求解刷tjb有什么用

**Comment by JavisPeng** [comment]
有个活动叫淘金币夺宝，最近可以抢茅台

**Comment by chimpan** [comment]
> 有个活动叫淘金币夺宝，最近可以抢茅台
纳尼，入口在哪里，没找到呢@@！

**Comment by chimpan** [comment]
@JavisPeng 纳尼，入口在哪里，没找到呀@@/

**Comment by moruoxian** [comment]
> 小白求解刷tjb有什么用

可以为国家电网做贡献哈哈哈

**Comment by JavisPeng** [comment]
chimpan 淘宝app直接搜索淘金币夺宝，但我昨天全输光了
