### ISSUE TITLE
跳槽

### ISSUE THREAD

**Issue by Aaronoooooo** [JavisPeng/taojinbi#29]
老哥年后跳槽了呀🌹

**Comment by JavisPeng** [comment]
嗯，想回老家了

**Comment by IShinji** [comment]
刚想问来不来我们这儿试试……

**Comment by JavisPeng** [comment]
@IShinji 贵公司是啥公司？

**Comment by IShinji** [comment]
> @IShinji 贵公司是啥公司？

网易有道

**Comment by JavisPeng** [comment]
@IShinji  我目前主要做人工智能图像这块，自然语言也研究过，还招人不？

**Comment by IShinji** [comment]
> @IShinji 我目前主要做人工智能图像这块，自然语言也研究过，还招人不？

肯定招呀，给我邮箱（见我Github主页）发个私人的联系方式。我们细聊？
