### ISSUE TITLE
==

### ISSUE THREAD

**Issue by ctt0124** [JavisPeng/taojinbi#30]
老哥我又来了。
cs_click(3, '#ff7d44', 0.1, 0.2, 0.5, 0.5, true); sleep(500) 
这里0.1 0.2 0.5的比例是怎么定的呀？
我想自己弄个京东的，不知道截图上找控件的时候怎么划分区域……

感激不尽~~~✿✿ヽ(°▽°)ノ✿

**Comment by JavisPeng** [comment]
0.1, 0.2, 0.5, 0.5  这几个参数就是左，上，右，下，相对手机的width和height的比例

**Comment by ctt0124** [comment]
我知道，但是怎么比划呢，用尺量吗………还是就估算一下。
