### ISSUE TITLE
能否有个开关，配置是否提醒好友收能量

### ISSUE THREAD

**Issue by heshangcode** [JavisPeng/taojinbi#33]
有时候并不想提醒好友收能量，但是我看代码似乎也被配置了，会去点那个提醒。

**Comment by JavisPeng** [comment]
新版的还有这个问题吗？ 之前我也注意到这个问题了，能量球的颜色和提醒好友太接近了，最新版我测试已经解决该问题了

**Comment by heshangcode** [comment]
> 新版的还有这个问题吗？ 之前我也注意到这个问题了，能量球的颜色和提醒好友太接近了，最新版我测试已经解决该问题了

新版已解决，牛逼，可以把这个 issue close 了，
