### ISSUE TITLE
报错问题

### ISSUE THREAD

**Issue by jw10126121** [JavisPeng/taojinbi#35]
get_collection_btn()方法，会出现返回null的情况，最好是返回

**Comment by jw10126121** [comment]
return list_btn_col[0]

**Comment by JavisPeng** [comment]
刚更新的版本应该不会有这个问题了，后面把单击函数替换为了
` btn_click(btn_col)`

**Comment by jw10126121** [comment]
1.5.5还是会有这个问题。刚发现的。。。 我试一下把tb更新到最新试一下

**Comment by JavisPeng** [comment]
@jw10126121 今天有时间，我再修复一下

**Comment by JavisPeng** [comment]
新版v1.5.6已经修复该问题
