### ISSUE TITLE
蚂蚁森林页面改版了，现在不能正常使用

### ISSUE THREAD

**Issue by heshangcode** [JavisPeng/taojinbi#36]
![image](https://user-images.githubusercontent.com/39662806/105489144-c2321a00-5ced-11eb-9ec7-ff051158e8ea.png)
最新状态这个去掉了，我自己试着改了一下，不行。
![image](https://user-images.githubusercontent.com/39662806/105489213-dbd36180-5ced-11eb-89a0-d38fc306d2ad.png)

**Comment by CNunicorn6** [comment]
把蚂蚁森林，喂小鸡和消消乐关闭掉就可以正常跑通了

**Comment by heshangcode** [comment]
> 把蚂蚁森林，喂小鸡和消消乐关闭掉就可以正常跑通了

我是直接点的单独执行蚂蚁森林找能量

**Comment by CNunicorn6** [comment]
>> > 把蚂蚁森林，喂小鸡和消消乐关闭掉就可以正常跑通了
>> 
>> 我是直接点的单独执行蚂蚁森林找能量
>
>那三个都有问题，估计要等作者更新下一个版本了

**Comment by JavisPeng** [comment]
新版已经兼容最新版支付宝蚂蚁森林
