### ISSUE TITLE
话费充值金

### ISSUE THREAD

**Issue by YYplus** [JavisPeng/taojinbi#38]
签到领取话费充值金增加弹窗导致任务卡住

**Comment by JavisPeng** [comment]
好的，周一有时间我再看看

**Comment by JavisPeng** [comment]
这个任务有点迷，可能是淘宝的BUG，我都没选择执行它，它却自动过去执行了，目前只有1个淘宝用户只能调试，明天再测试下

**Comment by YYplus** [comment]
![image](https://user-images.githubusercontent.com/65841378/105661631-de5dd300-5f08-11eb-92b0-f678643280b7.png)
我截了个图

**Comment by JavisPeng** [comment]
好的，谢谢截图，看日志这个薅羊毛是从‘’淘金币抵扣盛典”跳来的

**Comment by JavisPeng** [comment]
v1.5.7 该任务今天测试正常
