### ISSUE TITLE
借来的代码，仅供参考。 自动获取截图权限。 每次手动去点，麻烦

### ISSUE THREAD

**Issue by jayson8121** [JavisPeng/taojinbi#39]
function autoRequestScreenCapture(landscape) {
    //自定义按钮文本
    let capture_permission_button="";
    let countDown = new java.util.concurrent.CountDownLatch(1)
    let confirmWaitingThread = threads.start(function () {
        let confirmWidget = textMatches('START NOW|立即开始|允许').findOne(1000);
        if (confirmWidget) {
            sleep(200)
            let remember = id("android:id/checkbox").findOne(200);
            if (!remember) {
                remember = id("com.android.systemui:id/remember").findOne(200);
            }
            if (remember) {
                log('找到了记住按钮，点击记住')
                click(remember.bounds().centerX(),remember.bounds().centerY())
                sleep(200)
            } else {
                log('未找到记住按钮')
            }
            log('点击允许截图权限')
            click(confirmWidget.bounds().centerX(),confirmWidget.bounds().centerY())
        } else {
            log(['未找到允许截图按钮，查找内容为：{}', capture_permission_button || 'START NOW|立即开始|允许'], true)
            countDown.countDown()
        }
    })
    let requestSuccess = false
    let requestThread = threads.start(function () {
        requestSuccess = requestScreenCapture(landscape)
        countDown.countDown()
    })
    let waitResult = countDown.await(15, java.util.concurrent.TimeUnit.SECONDS)
    if (!waitResult) {
        log('请求截屏权限超时')
    }
    log('请求截屏权限结束：' + requestSuccess)
    confirmWaitingThread.interrupt()
    requestThread.interrupt()
    return requestSuccess
}

**Comment by JavisPeng** [comment]
有些人担心截图权限会悄悄录屏，这个权限还是给用户选择好

**Comment by jayson8121** [comment]
嗯，也对。
