### ISSUE TITLE
淘宝年货节任务 

### ISSUE THREAD

**Issue by hsh007** [JavisPeng/taojinbi#41]
我选择执行这个任务 然后从淘宝页面 进入淘金币 然后过了会就提示任务完成

**Comment by hsh007** [comment]
手机是mate20pro  分辨率设置的一样

**Comment by JavisPeng** [comment]
这个任务，建议单独执行，从淘金币过去，升级只加0.02%

**Comment by hsh007** [comment]
> 这个任务，建议单独执行，从淘金币过去，升级只加0.02％

我就是单独执行的。。。

![1](https://user-images.githubusercontent.com/22510558/105786325-ce50fc80-5fb7-11eb-8a6f-134cf2ae2fcd.jpg)
![2](https://user-images.githubusercontent.com/22510558/105786329-d01ac000-5fb7-11eb-92d1-8c71c14df48f.jpg)

**Comment by hsh007** [comment]
> 这个任务，建议单独执行，从淘金币过去，升级只加0.02%

他每次都是 从淘宝 直接进淘金币 然后就停了一会  就执行结束了

**Comment by JavisPeng** [comment]
你在选择界面往下拉，在‘加载本地配置’按钮下面有个‘’单独执行年货节浇灌福气’按钮

**Comment by hsh007** [comment]
> 你在选择界面往下拉，在‘加载本地配置’按钮下面有个‘’单独执行年货节浇灌福气’按钮

哦哦 看到了 才发现 还可以下拉  ......
谢谢啦！
