### ISSUE TITLE
淘宝直播的脚本

### ISSUE THREAD

**Issue by rcfan1** [JavisPeng/taojinbi#42]
大佬，抽空做个淘宝直播（现在叫点淘）的脚本呗，可以直接提现，关键任务比较简单，估计花不了大佬多少时间，谢谢

**Comment by JavisPeng** [comment]
我下了一个APP看了下，有如下几个问题：
1. 有些任务居然要看10分钟，退出得重新开始看，手机可能一直开着
2. 模拟器和手机端的布局完全不一样

后期若有时间只考虑做模拟器端

**Comment by rcfan1** [comment]
> 我下了一个APP看了下，有如下几个问题：
> 
> 1. 有些任务居然要看10分钟，退出得重新开始看，手机可能一直开着
> 2. 模拟器和手机端的布局完全不一样
> 
> 后期若有时间只考虑做模拟器端

嗯，做模拟器端就可以，我现在就在模拟器里使用，用免root自动化助手做了个特别初级的脚本看直播视频，然后手动签到，步数和金蛋的任务，这几个收益就不错滴，期待大佬出个autojs高级脚本

**Comment by JavisPeng** [comment]
我今天做了下所有的任务，一天大概可以领3240个元宝，非新手后可以提现0.1元和10元，10天清空元宝，10000=1元，也就是说1天得赚1w元宝，你才能成功兑换10元，这坑太大了，我领了新人活动后，见好就收

**Comment by rcfan1** [comment]
其实我也没玩多久，已经提现15了。
但是从昨天开始，元宝数量大幅下降了，想要提现10元的确很难了，我也准备弃坑了。
再次感谢大佬
