### ISSUE TITLE
取消关注店铺

### ISSUE THREAD

**Issue by Aaronoooooo** [JavisPeng/taojinbi#43]
1.以前老版本可以,现在好像这个功能不行了
2.蹲一波注销店铺会员和芭芭农场集肥料功能
ps:淘金币好像买东西折扣很小,还有别的用途吗?

**Comment by JavisPeng** [comment]
关注店铺这个我明天看看
金币可以抽茅台，虽然没有中过

**Comment by Aaronoooooo** [comment]
> 关注店铺这个我明天看看
> 金币可以抽茅台，虽然没有中过

我觉得可以专注搞农场,虽然我不会,像比如说芭芭,东东农场,惊喜农场,苏宁农场,可以薅个小水果小零食啥的,哈哈哈,

**Comment by JavisPeng** [comment]
@Aaronoooooo  刚刚领了瓶洗衣液，年货的任务比较多，其他农场就几个任务
![0](https://user-images.githubusercontent.com/18676680/106082903-887e6a80-6156-11eb-8b14-1038898a6eca.jpg)

**Comment by Aaronoooooo** [comment]
哇哦哇哦

**Comment by Aaronoooooo** [comment]
> @Aaronoooooo 刚刚领了瓶洗衣液，年货的任务比较多，其他农场就几个任务
> ![0](https://user-images.githubusercontent.com/18676680/106082903-887e6a80-6156-11eb-8b14-1038898a6eca.jpg)

哇哦哇哦,是用阳光直接兑换吗

**Comment by JavisPeng** [comment]
不啊，就是淘宝年货节，施肥然后兑换
