### ISSUE TITLE
fucard报错

### ISSUE THREAD

**Issue by idelin** [JavisPeng/taojinbi#46]
![image](https://user-images.githubusercontent.com/23070481/106685533-88251a00-6603-11eb-9bf5-1b48a3995c0d.png)

**Comment by JavisPeng** [comment]
你的安卓是哪个版本的，低版本可能不兼容

**Comment by idelin** [comment]
9

**Comment by idelin** [comment]
安卓9 的话，应该怎么改

**Comment by JavisPeng** [comment]
我的是安卓10，理论上安卓9也支持autojs4.1跳转到短信列表界面啊，
