### ISSUE TITLE
fucard.js有问题

### ISSUE THREAD

**Issue by sd462355991111** [JavisPeng/taojinbi#47]
前提taojinbi.js可以用，应该不是我操作错误问题。
fucard.js改好手机号，运行，跳到支付宝，在搜索那里自动粘贴我的支付宝名字，然后跳到短信界面，然后一直在最上面的消费金待领取通知----服务提醒，这2个一直死循环，循环大概有几次后就停止，就这样。不能用

**Comment by sd462355991111** [comment]
红米k20p  安卓10，全面屏，网上查屏幕尺寸为1080x2340，跟你介绍页面的分辨率一样。

**Comment by sd462355991111** [comment]
最后提示脚本错误，并显示出脚本的路径。

**Comment by JavisPeng** [comment]
可能是手机问题，目前我只在P30Pro(华为系统)上测试通过，可能不支持小米
