### ISSUE TITLE
单独执行蚂蚁森林找能量，无法找到蚂蚁森林

### ISSUE THREAD

**Issue by heshangcode** [JavisPeng/taojinbi#48]
现在福卡 banner 出来了，导致找不到蚂蚁森林了。
![image](https://user-images.githubusercontent.com/39662806/106740560-8a17c900-6655-11eb-845b-d0c9a1d522fe.png)

**Comment by JavisPeng** [comment]
支付宝/淘宝，老喜欢添加新活动，我今天有时间修复下

**Comment by heshangcode** [comment]
> 支付宝/淘宝，老喜欢添加新活动，我今天有时间修复下

辛苦了，可以加个新活动的判断，这样下次这个新活动去掉了，会走原老逻辑
