### ISSUE TITLE
集福验证码问题

### ISSUE THREAD

**Issue by GOOD-AN** [JavisPeng/taojinbi#49]
我这边大约第12个的时候，一直提示获取验证码频繁。
链接是https://render.alipay.com/p/c/17yq18lq3slc?source=JIEFANG_RIBAO

**Comment by GOOD-AN** [comment]
据多次执行来看，大约10次以后会有高概率触发长时间不允许获取验证码的管控

**Comment by JavisPeng** [comment]
我这也是，第2天我才领完52个
