### ISSUE TITLE
漏任务没执行

### ISSUE THREAD

**Issue by uwhatsup** [JavisPeng/taojinbi#5]
1. 直播间看看任务没执行
2.淘宝人生任务没执行
3.省钱消消乐拿红包没执行
4.去天猫APP领红包任务，如果没有下载天猫APP的话 ，会卡着页面
5.双十二任务没有完全执行完毕就退出了

图片地址
https://imgchr.com/i/rF9Vfg

**Comment by JavisPeng** [comment]
新版本已经解决上面问题
