### ISSUE TITLE
k30以前可以这几次更新后不能用了，始终找不到首页

### ISSUE THREAD

**Issue by cnmhtt** [JavisPeng/taojinbi#54]

**Comment by JavisPeng** [comment]
K30是啥手机型号，我华为P30Pro今天早上测试正常，是找不到淘金币首页吗？

**Comment by cnmhtt** [comment]
![微信图片_20210222225323](https://user-images.githubusercontent.com/74138531/108724950-da9d8a80-7560-11eb-89eb-d8b19cafce41.jpg)

**Comment by cnmhtt** [comment]
redmi k30 5g 估计是分辨率的原因
