### ISSUE TITLE
脚本运行失败

### ISSUE THREAD

**Issue by Aaronoooooo** [JavisPeng/taojinbi#56]
![image](https://user-images.githubusercontent.com/46308307/108694683-533d2080-753a-11eb-87c3-495bc3678af8.png)

**Comment by JavisPeng** [comment]
687行啥都没有啊，js脚本是否没有下载完整？

**Comment by Aaronoooooo** [comment]
> 687行啥都没有啊，js脚本是否没有下载完整？
嗯嗯,就是无障碍模式时好时坏,跑一次就不行了

**Comment by JavisPeng** [comment]
我的autojs也是，免费版的原作者已经不维护了
