### ISSUE TITLE
大佬，增加一个芭芭农场行吗

### ISSUE THREAD

**Issue by 1348182031** [JavisPeng/taojinbi#6]
大佬，增加一个芭芭农场行吗，就是淘宝里面那个浇水领水果的

**Comment by 1348182031** [comment]
麻烦大佬了

**Comment by JavisPeng** [comment]
@1348182031 已经添加了啊，你的没执行吗？

**Comment by 1348182031** [comment]
> @1348182031 已经添加了啊，你的没执行吗？

大佬有交流群或者V.X群吗？有的时候提示OBJ为空，无可执行的简单浏览任务，就提示结束了

**Comment by JavisPeng** [comment]
@1348182031 芭芭农场是特殊任务，简单任务是简单的浏览任务，简单任务执行完成后，才执行特殊任务，双12后会把代码重新整理下，只保留淘金币代码
