### ISSUE TITLE
v1.6.0 小建议

### ISSUE THREAD

**Issue by Sirius2s** [JavisPeng/taojinbi#62]
:+1: 
:+1: 
新增的农场任务有点小建议：
1、由于首页可能没有农场频道入口，且现有动作在阳光农场点击果树进入时也会有未命中的情况；所以，建议通过从“我的淘宝”右上方“免费领水果”处进入。
![16BA0BD3D10C30F4A3B1B45EA26F5F67](https://user-images.githubusercontent.com/53803920/109587659-69eb0500-7b42-11eb-8d76-30cb49950f46.jpg)
2、任务列表下方有时会有直播或者浏览店铺的任务，有文字提示。如果麻烦的话就免了
![1](https://user-images.githubusercontent.com/53803920/109588418-a66b3080-7b43-11eb-89a2-7d9f8c098db2.jpg)

**Comment by Sirius2s** [comment]
另，步数任务老是卡；进入后点不点领取，停不停15S，该任务都不会成为完成状态；所以，能否给个参数设置来跳过这项?

**Comment by JavisPeng** [comment]
v1.6.1 已经更新，步数任务我今天是正常的，淘宝可能要升级到最新，
