### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by Aaronoooooo** [JavisPeng/taojinbi#64]
脚本功能越来越丰富了V587🌹🌹🌹
有个小意见,不知道工作量大不大:
把环境配置和启动脚本分开
1.环境配置单独一个脚本,里面可以配置自己想要那些执行的任务和参数
2.启动单独一个脚本,执行启动脚本去加载环境配置脚本的配置信息
这样可以借助auto.js上的定时任务功能,对启动脚本配置定时任务
ps:或者在现有的环境配置页面加一个类似老板键的功能,配置默认要执行的任务;这样就不用每次点完启动,在二次进行选择任务才执行脚本😄😄😄

**Comment by yyhkyo** [comment]
现在的脚本我的小米手机上打不开，要怎么修改才行呢

**Comment by JavisPeng** [comment]
目前比较忙，可能只能提供维护，不会在添加新功能

**Comment by JavisPeng** [comment]
@yyhkyo 打不开？是脚本报错吗

**Comment by Aaronoooooo** [comment]
> 现在的脚本我的小米手机上打不开，要怎么修改才行呢

复制粘贴的问题?重新下载后导入到auto.js中
