### ISSUE TITLE
芭芭农场的任务不能自动完成

### ISSUE THREAD

**Issue by qinyixi** [JavisPeng/taojinbi#65]
点击单独执行芭芭农场内全任务，只会打开淘宝，跳转到我的，然后就没有接下来的动作了，程序设计的话应该是点击该页面下的“芭芭农场”去收集阳光之类的，但是没有动作

**Comment by JavisPeng** [comment]
如果主页有芭芭农场话，我下个版本还是设置在主页吧，我的页面 有时会发生改变
