### ISSUE TITLE
执行芭芭农场有时没反应, 直接显示完成了

### ISSUE THREAD

**Issue by MatthewTt** [JavisPeng/taojinbi#66]
农场是合种的, 经常进入小程序后, 没反应直接提示完成任务了

**Comment by JavisPeng** [comment]
请问手机型号是？ 可能是手机分辨率不兼容导致

**Comment by MatthewTt** [comment]
> 请问手机型号是？ 可能是手机分辨率不兼容导致

三星s9 分辨率是2960*1440
最近几天是正常运行, 问题不大

**Comment by MatthewTt** [comment]
1
