### ISSUE TITLE
淘宝人生掷骰子任务失败

### ISSUE THREAD

**Issue by rosefun** [JavisPeng/taojinbi#67]
运行到 `toast_console('掷骰子任务-查看是否有神秘礼物(QTM的神秘)', true)`，程序就停止运行了。

设备：一加8

**Comment by JavisPeng** [comment]
我的最近也有这个问题，淘宝加载淘宝人生掷骰子太卡了，我先把等待时间设置长点，等淘宝人员优化吧，
