### ISSUE TITLE
逛好店得金币没有执行

### ISSUE THREAD

**Issue by aibeso** [JavisPeng/taojinbi#70]
逛好店得金币经常把浏览10s得能量的任务做了就返回，然后就不能自动执行逛好店的金币的任务了，建议可以从淘金币页面的逛店铺进入任务列表。荣耀v10

**Comment by JavisPeng** [comment]
这个是因为淘宝把任务名称的修改了，可自己在配置页面修改对应的关键字，或等我更新版本
