### ISSUE TITLE
大佬有淘宝下单脚本吗

### ISSUE THREAD

**Issue by solo052** [JavisPeng/taojinbi#71]
抢了个东西抢了半年了，实在抢不到。。我手工下单付款最少8秒，人家都是4秒内就付好款了，

**Comment by better319** [comment]
什么东西，说出来看看

**Comment by solo052** [comment]
就是能定时 把购物车的物品提交订单，进入付款页面就行了，，

**Comment by JavisPeng** [comment]
这个之前抢茅台的时候写个一个，淘宝有检测，重复点击多次就直接网络错误了
