### ISSUE TITLE
【建议】自动运行

### ISSUE THREAD

**Issue by sanmulaila** [JavisPeng/taojinbi#73]
是否可以设置脚本打开自动运行指定功能。
这样就可以在auto.js里面设置定时任务，然后每天自动执行了。

**Comment by Aaronoooooo** [comment]
> 是否可以设置脚本打开自动运行指定功能。
> 这样就可以在auto.js里面设置定时任务，然后每天自动执行了。

刚需😁

**Comment by JavisPeng** [comment]
这个功能没有研究过，后序有时间的话，可以试试
