### ISSUE TITLE
施肥进度

### ISSUE THREAD

**Issue by Aaronoooooo** [JavisPeng/taojinbi#74]
施肥一次增加0.01%,是不是号被黑了

**Comment by JavisPeng** [comment]
嗯，是的，我的也是，不过我在 v1.6.0 2021年3月1日19:07:42 提及了2种解决方法
关于芭芭农场升级0.01%的2种解决方法：
1. 方法1=在淘宝中执行任务后，关闭autojs,在支付宝中升级；
2. 方法2=在手机应用设置中清除淘宝的本地数据，重新登录后再升级 (推荐方法1)
