### ISSUE TITLE
【1.6.5版本】淘X人生、消消乐还是运行不正常

### ISSUE THREAD

**Issue by solo052** [JavisPeng/taojinbi#75]
淘金币中消消乐一进到游戏页面就需确认是否离开，淘宝人生不能掷筛子。

**Comment by Wolverinetracy** [comment]
消消乐其实没必要做进来直接放个类似于黑名单好了，还有那个掷骰子好像也不行，不知道是不是个人手机原因。还有个建议能不能加做个芭芭农场，里面的阳光农场

**Comment by fatmeat** [comment]
消消樂各個版本都試過, 一樣運行不正常

**Comment by solo052** [comment]
芭芭农场  可以写个脚本吗，还有个（浏览好店送金币）关注店铺会送10金币，有几个店铺还会出现5金币，能不能一起写下脚本

**Comment by JavisPeng** [comment]
@mangodmai  消消乐版本升级了，只能点击左上角的返回图标才能返回了，下个版本会修复

**Comment by JavisPeng** [comment]
@solo052 这个好像是随机的，我这好像没有，请手动点击吧
