### ISSUE TITLE
如何获得淘金币最新版app？

### ISSUE THREAD

**Issue by lsmm2021** [JavisPeng/taojinbi#77]
感觉很好用，靠软件翻译来的，请问如何获得淘金币最新版app？找不到apk下载链接。

谢谢。

**Comment by lsmm2021** [comment]
等待中~~~~

**Comment by JavisPeng** [comment]
下载链接：https://github.com/JavisPeng/taojinbi/releases

**Comment by lsmm2021** [comment]
已下载使用，感觉不如之前的版本稳定，出现红字终止。
记不得具体版本，打开就能运行，不需要开启无障碍。
