### ISSUE TITLE
有计划写一个活力中心的脚本吗

### ISSUE THREAD

**Issue by ghost** [JavisPeng/taojinbi#8]
大佬，有计划写个活力中心的脚本吗？也是淘宝的，不过是活力中心的，功能类似

**Comment by JavisPeng** [comment]
@ABBCzar 活力中心？这个任务在哪？ 截个图瞅瞅

**Comment by ABBCzar** [comment]
![Uploading 354e7a781423beb98ee8ca7030d6e1d06ce8b369.jpg…]()

**Comment by ghost** [comment]
https://jingyan.baidu.com/article/02027811a5fccb5acc9ce59a.html

**Comment by ghost** [comment]
入口还是一样的，在我的淘宝-活力中心，游戏的脚本可能会比较难

**Comment by JavisPeng** [comment]
@ABBCzar 下一个版本会在淘金币执行完成后附加活力中心任务，目前打算复用现有的代码，游戏任务暂时不实现

**Comment by JavisPeng** [comment]
@ABBCzar v1.3.0已经附加活力中心任务

**Comment by ghost** [comment]
好的，我试试
