### ISSUE TITLE
大大，能否增加更多的任务，是脚本更加完善呢？

### ISSUE THREAD

**Issue by JING20212** [JavisPeng/taojinbi#84]
1、天猫超市每日翻卡
2、天猫超市-我的-刮刮喵晶
3、淘宝每日签到红包
4、芭芭农场种地的那个界面
5、淘宝吃货每日签到，一元领10个鸡蛋
6、活力中心任务
7、菜鸟每日签到
8、裹酱任务

最后，谢谢大大的辛苦付出！！！

**Comment by JavisPeng** [comment]
个人精力有限，目前只考虑维护淘金币任务
