### ISSUE TITLE
消消樂問題

### ISSUE THREAD

**Issue by fatmeat** [JavisPeng/taojinbi#85]
大佬, 每次消消樂只會消除兩次, 任務要三次呢~~另恭喜終於更新了~~

**Comment by JavisPeng** [comment]
这就奇怪来，我这执行都是三次。有可能和手机分辨率有关，你的手机是啥型号？

**Comment by fatmeat** [comment]
OnePlus 8T

**Comment by andy31009** [comment]
大佬，我的手机型号是华为荣耀10，一次都消不了

**Comment by xu19710308** [comment]
怎么下载是1.55版本，1.67找不到连

**Comment by JavisPeng** [comment]
@xu19710308 启动器是1.55版本，执行脚本是1.6.7

**Comment by JavisPeng** [comment]
@andy31009 可能是手机分辨率问题，计算位置的时候有些偏差

**Comment by xu19710308** [comment]
> @xu19710308 启动器是1.55版本，执行脚本是1.6.7

谢谢
