### ISSUE TITLE
模拟器中运行报错

### ISSUE THREAD

**Issue by spoonwep** [JavisPeng/taojinbi#86]
已经开启了无障碍，点击运行后如下图报错

<img width="387" alt="WX20210429-144655@2x" src="https://user-images.githubusercontent.com/4607506/116513654-831ef080-a8fc-11eb-8976-d9967d5f291f.png">

**Comment by better319** [comment]
我想问这个淘金币有什么用处啊，我都已经好多了。。

**Comment by spoonwep** [comment]
@better319 很多东西都可以淘金币抵扣现金的啊

**Comment by JavisPeng** [comment]
目前暂时不支持模拟器，实测会被淘宝拉黑
