### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by jw10126121** [JavisPeng/taojinbi#9]
`            while (!btn_x) {
                console.log('等待进入淘宝首页..(若长时间等待请手动进入淘宝首页)');
                btn_x = desc('领淘金币').findOne(1000)
            }
`
这边，如果获取不到”领淘金币“按钮，是不是自动返回到taobao首页比较好？

**Comment by jw10126121** [comment]
判断currentActivity() != "com.taobao.tao.TBMainActivity"，就back()，递归，然后再重新找'领淘金币'按钮。。

**Comment by JavisPeng** [comment]
感谢提示，代码已经修改如
```
let num = 8
while (num-- && !desc('领淘金币').findOne(1000)) back();
```
