### ISSUE TITLE
三个bug

### ISSUE THREAD

**Issue by MarsTLBAD** [JavisPeng/taojinbi#95]
1.浏览精选宝贝：宝贝页面需要向下不停的滑动，系统才能判定浏览成功，而不是原地等待15s
2.去天猫APP领红包（4/5）：天猫APP页面内浏览时间未满15s就返回了，任务未完成
3.逛省钱消消乐拿红包（0/1）：需要完成消除三次才能完成任务，而不是直接退出关卡

**Comment by andy31009** [comment]
> 1.浏览精选宝贝：宝贝页面需要向下不停的滑动，系统才能判定浏览成功，而不是原地等待15s
> 2.去天猫APP领红包（4/5）：天猫APP页面内浏览时间未满15s就返回了，任务未完成
> 3.逛省钱消消乐拿红包（0/1）：需要完成消除三次才能完成任务，而不是直接退出关卡

在我的手机上第1个没问题，第2、3个也是同样的问题

**Comment by JavisPeng** [comment]
前2个，我这测试没有问题，第3个可能和手机型号有关，建议手动运行
3.逛省钱消消乐拿红包（0/1）：需要完成消除三次才能完成任务，而不是直接退出关卡
