### ISSUE TITLE
仨小问题

### ISSUE THREAD

**Issue by 67here** [JavisPeng/taojinbi#97]
1.消消乐 进去了啥也没干 直接退出
2.掷骰子 掷不出来
3.农场完不成 不施肥

其它都运行的很好
魅族16sp flyme8.0.0

**Comment by 67here** [comment]
详细点说，消消乐变成了3下才能完成
农场要先领 后施肥
小说的10s 变成了进去看小说文本内容 才开始计时

**Comment by pblearning** [comment]
逛猜你喜欢的商品 需要下滑15s才算完成任务，脚本进去之后没有下滑等待15S就出来了，一直循环，一直卡在这个任务上。
消消乐和小说也是有问题，都是无限循环。

**Comment by 975914892** [comment]
同样，无法下滑，卡任务了

**Comment by 67here** [comment]
> 同样，无法下滑，卡任务了

pull request那里 有这个下滑的解决方案
